create table if not exists public.telemetry_map_cache_entries (
  id bigint generated by default as identity primary key,
  match_id text not null,
  platform text not null check (platform in ('steam', 'kakao')),
  player_id text not null,
  mode text not null check (mode in ('lite', 'full')),
  telemetry_version numeric not null,
  storage_path text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, platform, player_id, mode, telemetry_version)
);

create index if not exists telemetry_map_cache_entries_match_id_idx
  on public.telemetry_map_cache_entries (match_id);

create index if not exists telemetry_map_cache_entries_updated_at_idx
  on public.telemetry_map_cache_entries (updated_at);

alter table public.telemetry_map_cache_entries enable row level security;
revoke all on table public.telemetry_map_cache_entries from anon, authenticated;
grant select, insert, update, delete on table public.telemetry_map_cache_entries to service_role;

create or replace function public.cleanup_expired_telemetry_matches(
  p_match_ids text[],
  p_cutoff timestamptz,
  p_target_version numeric
)
returns table(match_id text)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  eligible_match_ids text[];
begin
  if p_match_ids is null
    or p_cutoff is null
    or p_target_version is null
    or cardinality(p_match_ids) > 50
  then
    raise exception 'telemetry-cleanup-invalid-rpc-input' using errcode = '22023';
  end if;

  lock table public.telemetry_map_cache_entries
    in share row exclusive mode;

  perform 1
  from public.match_master_telemetry as master
  where master.match_id = any(p_match_ids)
  order by master.match_id
  for update;

  perform 1
  from public.telemetry_map_cache_entries as cache
  where cache.match_id = any(p_match_ids)
  order by cache.id
  for update;

  select coalesce(
    array_agg(master.match_id order by master.match_id),
    array[]::text[]
  )
  into eligible_match_ids
  from public.match_master_telemetry as master
  where master.match_id = any(p_match_ids)
    and (
      master.telemetry_version < p_target_version
      or master.created_at < p_cutoff
    )
    and not exists (
      select 1
      from public.telemetry_map_cache_entries as cache
      where cache.match_id = master.match_id
        and cache.updated_at >= p_cutoff
    );

  if cardinality(eligible_match_ids) = 0 then
    return;
  end if;

  delete from public.match_stats_raw as stats
  where stats.match_id = any(eligible_match_ids);

  delete from public.processed_match_telemetry as processed
  where processed.match_id = any(eligible_match_ids);

  delete from public.telemetry_map_cache_entries as cache
  where cache.match_id = any(eligible_match_ids)
    and cache.updated_at < p_cutoff;

  return query
  delete from public.match_master_telemetry as master
  where master.match_id = any(eligible_match_ids)
    and (
      master.telemetry_version < p_target_version
      or master.created_at < p_cutoff
    )
    and not exists (
      select 1
      from public.telemetry_map_cache_entries as cache
      where cache.match_id = master.match_id
    )
  returning master.match_id;
end;
$$;

revoke all on function public.cleanup_expired_telemetry_matches(text[], timestamptz, numeric)
  from public, anon, authenticated;
grant execute on function public.cleanup_expired_telemetry_matches(text[], timestamptz, numeric)
  to service_role;
