create table if not exists public.telemetry_map_cache_entries (
  id bigint generated by default as identity primary key,
  match_id text not null,
  platform text not null check (platform in ('steam', 'kakao')),
  player_id text not null,
  mode text not null check (mode in ('lite', 'full')),
  telemetry_version numeric not null,
  storage_path text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, platform, player_id, mode, telemetry_version)
);

create index if not exists telemetry_map_cache_entries_match_id_idx
  on public.telemetry_map_cache_entries (match_id);

create index if not exists telemetry_map_cache_entries_updated_at_idx
  on public.telemetry_map_cache_entries (updated_at);

alter table public.telemetry_map_cache_entries enable row level security;
revoke all on table public.telemetry_map_cache_entries from anon, authenticated;
grant select, insert, update, delete on table public.telemetry_map_cache_entries to service_role;
