create table if not exists public.telemetry_map_cache_entries (
  id bigint generated by default as identity primary key,
  match_id text not null,
  platform text not null check (platform in ('steam', 'kakao')),
  player_id text not null,
  mode text not null check (mode in ('lite', 'full')),
  telemetry_version numeric not null,
  storage_path text not null unique,
  status text not null default 'pending' check (status in ('pending', 'ready')),
  lease_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, platform, player_id, mode, telemetry_version)
);

create index if not exists telemetry_map_cache_entries_match_id_idx
  on public.telemetry_map_cache_entries (match_id);

create index if not exists telemetry_map_cache_entries_updated_at_idx
  on public.telemetry_map_cache_entries (updated_at);

create index if not exists telemetry_map_cache_entries_lease_idx
  on public.telemetry_map_cache_entries (status, lease_expires_at);

alter table public.telemetry_map_cache_entries enable row level security;
revoke all on table public.telemetry_map_cache_entries from anon, authenticated;
grant select, insert, update, delete on table public.telemetry_map_cache_entries to service_role;

do $$
declare
  identity_sequence text;
begin
  identity_sequence := pg_get_serial_sequence(
    'public.telemetry_map_cache_entries',
    'id'
  );
  if identity_sequence is null then
    raise exception 'telemetry-cache-identity-sequence-missing';
  end if;
  execute format(
    'revoke all on sequence %s from public, anon, authenticated',
    identity_sequence
  );
  execute format(
    'grant usage, select on sequence %s to service_role',
    identity_sequence
  );
end;
$$;

create or replace function public.finalize_telemetry_cache_write(
  p_match_id text,
  p_map_name text,
  p_game_mode text,
  p_master_version numeric,
  p_storage_path text,
  p_platform text,
  p_player_id text,
  p_mode text,
  p_cache_version numeric,
  p_cache_updated_at timestamptz,
  p_processed_player_id text,
  p_processed_platform text,
  p_processed_data jsonb,
  p_processed_updated_at timestamptz
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if p_match_id is null
    or p_map_name is null
    or p_game_mode is null
    or p_master_version is null
    or p_storage_path is null
    or p_platform not in ('steam', 'kakao')
    or p_player_id is null
    or p_mode not in ('lite', 'full')
    or p_cache_version is null
    or p_cache_updated_at is null
    or not (
      (
        p_processed_player_id is null
        and p_processed_platform is null
        and p_processed_data is null
        and p_processed_updated_at is null
      )
      or (
        p_processed_player_id is not null
        and p_processed_platform is not null
        and p_processed_data is not null
        and p_processed_updated_at is not null
      )
    )
  then
    raise exception 'telemetry-finalize-invalid-input' using errcode = '22023';
  end if;

  if p_processed_data is not null then
    insert into public.processed_match_telemetry (
      match_id,
      platform,
      player_id,
      data,
      updated_at
    ) values (
      p_match_id,
      p_processed_platform,
      p_processed_player_id,
      p_processed_data,
      p_processed_updated_at
    )
    on conflict (match_id, platform, player_id) do update set
      data = excluded.data,
      updated_at = excluded.updated_at;
  end if;

  insert into public.match_master_telemetry (
    match_id,
    map_name,
    game_mode,
    telemetry_version,
    storage_path
  ) values (
    p_match_id,
    p_map_name,
    p_game_mode,
    p_master_version,
    p_storage_path
  )
  on conflict (match_id) do update set
    map_name = excluded.map_name,
    game_mode = excluded.game_mode,
    telemetry_version = excluded.telemetry_version,
    storage_path = excluded.storage_path;

  insert into public.telemetry_map_cache_entries (
    match_id,
    platform,
    player_id,
    mode,
    telemetry_version,
    storage_path,
    status,
    lease_expires_at,
    updated_at
  ) values (
    p_match_id,
    p_platform,
    p_player_id,
    p_mode,
    p_cache_version,
    p_storage_path,
    'ready',
    null,
    p_cache_updated_at
  )
  on conflict (match_id, platform, player_id, mode, telemetry_version) do update set
    storage_path = excluded.storage_path,
    status = excluded.status,
    lease_expires_at = excluded.lease_expires_at,
    updated_at = excluded.updated_at;
end;
$$;

revoke all on function public.finalize_telemetry_cache_write(
  text, text, text, numeric, text, text, text, text, numeric,
  timestamptz, text, text, jsonb, timestamptz
) from public, anon, authenticated;
grant execute on function public.finalize_telemetry_cache_write(
  text, text, text, numeric, text, text, text, text, numeric,
  timestamptz, text, text, jsonb, timestamptz
) to service_role;

create or replace function public.cleanup_expired_telemetry_matches(
  p_match_ids text[],
  p_cutoff timestamptz,
  p_target_version numeric
)
returns table(match_id text)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  eligible_match_ids text[];
begin
  if p_match_ids is null
    or p_cutoff is null
    or p_target_version is null
    or cardinality(p_match_ids) > 50
  then
    raise exception 'telemetry-cleanup-invalid-rpc-input' using errcode = '22023';
  end if;

  lock table public.telemetry_map_cache_entries
    in share row exclusive mode;

  perform 1
  from public.match_master_telemetry as master
  where master.match_id = any(p_match_ids)
  order by master.match_id
  for update;

  perform 1
  from public.telemetry_map_cache_entries as cache
  where cache.match_id = any(p_match_ids)
  order by cache.id
  for update;

  select coalesce(
    array_agg(requested.match_id order by requested.match_id),
    array[]::text[]
  )
  into eligible_match_ids
  from unnest(p_match_ids) as requested(match_id)
  left join public.match_master_telemetry as master
    on master.match_id = requested.match_id
  where (
      (
        master.match_id is not null
        and (
          master.telemetry_version < p_target_version
          or master.created_at < p_cutoff
        )
      )
      or (
        master.match_id is null
        and exists (
          select 1
          from public.telemetry_map_cache_entries as orphan_cache
          where orphan_cache.match_id = requested.match_id
            and orphan_cache.updated_at < p_cutoff
            and not (
              orphan_cache.status = 'pending'
              and orphan_cache.lease_expires_at >= statement_timestamp()
            )
        )
      )
    )
    and not exists (
      select 1
      from public.telemetry_map_cache_entries as cache
      where cache.match_id = requested.match_id
        and (
          (cache.status = 'ready' and cache.updated_at >= p_cutoff)
          or (
            cache.status = 'pending'
            and cache.lease_expires_at >= statement_timestamp()
          )
        )
    );

  if cardinality(eligible_match_ids) = 0 then
    return;
  end if;

  delete from public.match_stats_raw as stats
  where stats.match_id = any(eligible_match_ids);

  delete from public.processed_match_telemetry as processed
  where processed.match_id = any(eligible_match_ids);

  delete from public.telemetry_map_cache_entries as cache
  where cache.match_id = any(eligible_match_ids)
    and cache.updated_at < p_cutoff
    and not (
      cache.status = 'pending'
      and cache.lease_expires_at >= statement_timestamp()
    );

  delete from public.match_master_telemetry as master
  where master.match_id = any(eligible_match_ids)
    and (
      master.telemetry_version < p_target_version
      or master.created_at < p_cutoff
    )
    and not exists (
      select 1
      from public.telemetry_map_cache_entries as cache
      where cache.match_id = master.match_id
    )
  ;

  return query
  select eligible.match_id
  from unnest(eligible_match_ids) as eligible(match_id)
  order by eligible.match_id;
end;
$$;

revoke all on function public.cleanup_expired_telemetry_matches(text[], timestamptz, numeric)
  from public, anon, authenticated;
grant execute on function public.cleanup_expired_telemetry_matches(text[], timestamptz, numeric)
  to service_role;
