-- 비회원 게시판 및 모더레이션 시스템 마이그레이션
-- posts/comments 비회원 보안 컬럼, 신고 테이블, IP 차단 테이블

-- 1. posts/comments 비회원 보안 컬럼 추가
ALTER TABLE posts ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS ip_address text;
ALTER TABLE comments ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE comments ADD COLUMN IF NOT EXISTS ip_address text;

-- 2. post_status ENUM에 'hidden' 추가 (블라인드용)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_enum
    WHERE enumlabel = 'hidden'
    AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'post_status')
  ) THEN
    ALTER TYPE post_status ADD VALUE 'hidden';
  END IF;
END $$;

-- 3. 신고 내역 관리 테이블
CREATE TABLE IF NOT EXISTS public.reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type text NOT NULL CHECK (target_type IN ('post', 'comment')),
    target_id bigint NOT NULL,
    reason text NOT NULL,
    detail text,
    reporter_ip text,
    reporter_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'dismissed')),
    admin_note text,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- 4. IP 차단 관리 테이블
CREATE TABLE IF NOT EXISTS public.ip_blacklist (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address text UNIQUE NOT NULL,
    reason text,
    expires_at timestamptz,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- 5. RLS 정책 설정
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ip_blacklist ENABLE ROW LEVEL SECURITY;

-- 신고 생성은 누구나 가능 (비회원 포함)
CREATE POLICY "Allow public insert reports" ON public.reports
    FOR INSERT WITH CHECK (true);

-- 신고 조회/수정/삭제는 어드민만 가능
CREATE POLICY "Allow admin manage reports" ON public.reports
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );

-- IP 차단 관리는 어드민만 가능
CREATE POLICY "Allow admin manage blacklist" ON public.ip_blacklist
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );

-- 6. hidden 상태 게시글 일반 노출 차단 (기존 정책 교체)
DROP POLICY IF EXISTS "Allow public read published posts" ON posts;
CREATE POLICY "Allow public read published posts" ON posts
    FOR SELECT USING (status = 'published');
